channels:
- conda-forge
dependencies:
- lammps =2024.06.27=*openmpi*
- openmpi =4.1.6
- pandas =2.3.2
- pylammpsmpi =0.2.39
- jinja2 =3.1.6
- iprpy-data =2023.07.25
- dynaphopy =1.17.16
- pyiron_lammps =0.4.5
