channels:
- conda-forge
dependencies:
- ase =3.22.1
- dynaphopy =1.17.5
- gpaw =20.1.0
- iprpy-data =2023.07.25
- jinja2 =2.11.3
- lammps =2022.06.23
- lxml =4.9.1
- mendeleev =0.12.0
- numpy =1.23.5
- pandas =2.0.3
- phonopy =2.20.0
- pylammpsmpi =0.2.1
- requests =2.24.0
- scipy =1.11.1
- seekpath =1.9.0
- spglib =2.0.2
- structuretoolkit =0.0.10
- tqdm =4.44.0
- pyiron_lammps =0.3.2