name: Coverage Linux Python 3.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge Notebook environment
      run: |
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add .ci_support/environment-coverage.yml > environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: coverage run --omit atomistics/_version.py -m unittest discover tests
      env:
        ASE_ESPRESSO_COMMAND: "mpirun -np 1 pw.x -in PREFIX.pwi > PREFIX.pwo"
        ESPRESSO_PSEUDO: tests/static/qe
        OMPI_MCA_plm: isolated
        OMPI_MCA_btl_vader_single_copy_mechanism: none
        OMPI_MCA_rmaps_base_oversubscribe: yes
    - name: Coverage
      continue-on-error: True
      shell: bash -l {0}
      run: |
        coverage combine
        coveralls
        coverage xml
    - name: Codacy
      if: github.event_name != 'push'
      continue-on-error: True
      shell: bash -l {0}
      run: |
        python-codacy-coverage -r coverage.xml
