name: MatGL Unittest Linux 3.12

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Merge Notebook environment
      run: |
        cp .ci_support/environment.yml environment.yml
        tail --lines=+4 .ci_support/environment-matgl.yml >> environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.12'
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 60
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        python -m unittest tests/test_ase_interface/test_evcurve_ase_matgl.py
        python -m unittest tests/test_ase_interface/test_phonons_ase_matgl.py
        python -m unittest tests/test_ase_interface/test_quasiharmonic_ase_matgl.py
        python -m unittest tests/test_ase_interface/test_ase_md_matgl.py
